# Generated by Django 5.0.2 on 2024-02-13 07:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('transaction', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accounting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transactions_type', models.CharField(choices=[('Purchase', 'Purchase'), ('Sales', 'Sales'), ('Adjustment', 'Adjustment')], default='Sales', max_length=300)),
                ('transaction_date', models.DateField()),
                ('debit_amt', models.IntegerField(blank=True, null=True)),
                ('credit_amt', models.IntegerField(blank=True, null=True)),
                ('transactions_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transaction.inventory_transaction')),
            ],
        ),
    ]
